apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-webhook
  namespace: argo-events
spec:
  service:
    ports:
      - name: webhook
        port: 12000
        targetPort: 12000
  template:
    serviceAccountName: argo-events-sa
    podSpecPatch: |
      [
        {
          "op": "add",
          "path": "/containers/-",
          "value": {
            "name": "smee-relay",
            "image": "ghcr.io/${GIT_USERNAME}/smee-relay:latest",
            "imagePullPolicy": "IfNotPresent",
            "env": [
              {
                "name": "SMEE_URL",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "smee-relay-url",
                    "key": "url"
                  }
                }
              },
              {
                "name": "SMEE_TARGET",
                "value": "http://127.0.0.1:12000/payload"
              }
            ]
          }
        }
      ]
  webhook:
    repo-push:
      port: "12000"
      method: POST
      endpoint: /payload
      authSecret:
        name: github-webhook-secret
        key: token
